version: '3'
services:
  app:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: "npm run start"
    depends_on:
      - database

  database:
    image: mongo:4.4
    ports:
      - "27017:27017"